# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = labels
mod_name = Storage Labels
mod_version = 1.21-2.0.3
mod_author = MehVahdJukaar
mod_description = Label everything!
mod_license = Supplementaries Team License v.1.5
mod_authors = MehVahdJukaar, Plantkillable
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/labels
mod_credits = MehVahdJukaar, Plantkillable
mod_github = https://github.com/MehVahdJukaar/labels-multi

release_type = release
maven_group = net.mehvahdjukaar

# Publishing
repository = MehVahdJukaar/labels-multi
modrinth_project_id = labels
curseforge_project_id = 688223

# MC / loader versions
mc_version = 1.21.1

neoforge_version = 21.1.228

fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1

parchment_mappings_version = 2024.11.17

# Other deps
moonlight_version = 1.21.1-3.0.11
moonlight_min_version = 1.21-2.29.17

modmenu_version = 4.0.6
flywheel_version = 1.21.1:1.0.0-9
